//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.Group_Menu = new HashSet<Group_Menu>();
        }
    
        public long Id { get; set; }
        public string Menu_Name { get; set; }
        public string Menu_Action { get; set; }
        public string Menu_Controller { get; set; }
        public string Menu_Icon { get; set; }
        public Nullable<long> Parent { get; set; }
        public Nullable<int> Ordinal { get; set; }
        public Nullable<bool> Visible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group_Menu> Group_Menu { get; set; }
    }
}
