//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        public long Id { get; set; }
        public long Order_Id { get; set; }
        public string Product_Name { get; set; }
        public decimal Product_Qty { get; set; }
        public string Product_UOM { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Edit_By { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
