//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeaderDetail
    {
        public long Id { get; set; }
        public Nullable<long> Header_Id { get; set; }
        public Nullable<long> Book_Id { get; set; }
        public Nullable<long> Stationary_Id { get; set; }
        public decimal Quantity { get; set; }
        public decimal Qty_Stationary { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Edit_By { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public string Delete_By { get; set; }
        public Nullable<bool> Is_Book_Deleted { get; set; }
        public Nullable<bool> Is_Stationary_Deleted { get; set; }
    }
}
