//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stationary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stationary()
        {
            this.Stationary_Detail = new HashSet<Stationary_Detail>();
            this.Stationary_Product = new HashSet<Stationary_Product>();
        }
    
        public long Id { get; set; }
        public string Transaction_No { get; set; }
        public System.DateTime Transaction_Date { get; set; }
        public long Customer_Id { get; set; }
        public string Customer_Address { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Edit_By { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public string Delete_By { get; set; }
        public string Is_Delete { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stationary_Detail> Stationary_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stationary_Product> Stationary_Product { get; set; }
    }
}
