//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.User_Group = new HashSet<User_Group>();
        }
    
        public long Id { get; set; }
        public string Employee_Number { get; set; }
        public string Full_Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool Is_Admin { get; set; }
        public bool Use_AD { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Edited_By { get; set; }
        public Nullable<System.DateTime> Edited_Date { get; set; }
        public Nullable<System.DateTime> Last_Access_Date { get; set; }
        public string Is_Deleted { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
        public string Deleted_By { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Group> User_Group { get; set; }
    }
}
